### ISSUE TITLE
Support `--ignore-package` and `--ignore-code` flags

### ISSUE THREAD

**Issue by simon-liebehenschel** [koyeung/ko-poetry-audit-plugin#27]
https://github.com/opeco17/poetry-audit-plugin#available-options

**Comment by koyeung** [comment]
Thanks for the suggestion. Allow bypass might cause issue if they are really issue in future and forgot to remove the bypass from command line.

any idea if writing a JSON output and accept/ignore the finding explicitly, outside the "audit" command?

Pls open a PR if it could be helpful.
